### ISSUE TITLE
Issue installing on Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by mother2110** [secretsquirrel/the-backdoor-factory#72]
I get the following issue when running backdoor.py. I ran the install.py as well.

[root:...entest/the-backdoor-factory]# ./backdoor.py                 (master✱) 
Traceback (most recent call last):
  File "./backdoor.py", line 52, in <module>
    from pebin import pebin
  File "/opt/pentest/the-backdoor-factory/pebin.py", line 50, in <module>
    from intel.intelCore import intelCore
  File "/opt/pentest/the-backdoor-factory/intel/intelCore.py", line 38, in <module>
    from capstone import *
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
[root:...entest/the-backdoor-factory]#                               (master✱)

**Comment by secretsquirrel** [comment]
Capstone did not fully install. Good luck!

**Comment by mother2110** [comment]
Thanks. You were correct. It is working now.
